#!/bin/sh
# Recreate the source trees this port builds against.
#
#   bootstrap-sources.sh
#
# Everything here is reproducible from two pinned inputs, so none of it needs
# backing up:
#
#   kernel/linux-6.18.42.tar.xz      official upstream tarball; kept only as
#                                    the source of the pristine tree below.
#                                    Buildroot fetches its own copy from
#                                    kernel.org into the download volume
#   buildroot/buildroot-2026.02.3/   extracted from a checksum-pinned tarball
#
# and one derived tree:
#
#   kernel/linux-6.18.42-pristine/   never modified; the reference the patch
#                                    queue in br2-external/board/dhb-ax/patches
#                                    is diffed against
#
# Buildroot extracts and patches its own copy of the kernel on every build, so
# there is no persistent build tree here any more and no --reset-build.  The
# whole class of "tree carrying a superseded patch" problem went with it.
set -eu

workspace=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
kernel_dir=$workspace/kernel
buildroot_dir=$workspace/buildroot

version=6.18.42
tarball=$kernel_dir/linux-$version.tar.xz
tarball_url=https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$version.tar.xz
pristine=$kernel_dir/linux-$version-pristine

# 2026.02 is the LTS line, which suits a project picked up intermittently.
# The checksum is the one in the release's PGP-signed manifest at
# https://buildroot.org/downloads/buildroot-2026.02.3.tar.xz.sign
br_version=2026.02.3
br_tarball=$buildroot_dir/buildroot-$br_version.tar.xz
br_tarball_url=https://buildroot.org/downloads/buildroot-$br_version.tar.xz
br_sha256=5a59e7501b0b4ec52c41f4bfa79412320e0b37eae5f719605a258e8d0c6fc7fb
br_src=$buildroot_dir/buildroot-$br_version

mkdir -p "$kernel_dir" "$buildroot_dir"

if [ ! -f "$tarball" ]; then
	echo "fetching $tarball_url"
	curl --fail --location "$tarball_url" --output "$tarball"
fi

# Kept for one reason: patches are generated by diffing against it.  Buildroot
# never looks at this tree.
if [ ! -f "$pristine/Makefile" ]; then
	echo "extracting pristine tree"
	rm -rf "$pristine"
	mkdir -p "$pristine"
	tar -xJf "$tarball" -C "$pristine" --strip-components=1
fi

if [ ! -f "$br_tarball" ]; then
	echo "fetching $br_tarball_url"
	curl --fail --location "$br_tarball_url" --output "$br_tarball"
fi

# The tarball is unpacked into a tree the build then treats as read-only, so
# verify it once here rather than trusting whatever is on disk.
if command -v sha256sum >/dev/null 2>&1; then
	got=$(sha256sum "$br_tarball" | cut -d' ' -f1)
else
	got=$(shasum -a 256 "$br_tarball" | cut -d' ' -f1)
fi
if [ "$got" != "$br_sha256" ]; then
	echo "checksum mismatch for $br_tarball" >&2
	echo "  expected $br_sha256" >&2
	echo "  got      $got" >&2
	echo "delete the file and re-run to fetch it again" >&2
	exit 1
fi

if [ ! -f "$br_src/Makefile" ]; then
	echo "extracting Buildroot $br_version"
	rm -rf "$br_src"
	tar -xJf "$br_tarball" -C "$buildroot_dir"
fi

echo
echo "ready:"
printf '  %-34s %s\n' "kernel tarball" "$tarball"
printf '  %-34s %s\n' "kernel source (patch reference)" "$pristine"
printf '  %-34s %s\n' "buildroot $br_version" "$br_src"
echo
echo "build with: scripts/buildroot.sh"
