FROM debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install --yes --no-install-recommends \
        ca-certificates \
        debian-archive-keyring \
        dropbear-bin \
        gpg \
        kmod \
        mmdebstrap \
        openssh-client \
        systemd \
    && rm -rf /var/lib/apt/lists/*

COPY debian-rootfs-in-container.sh /usr/local/sbin/dhb-ax-debian-rootfs

ENTRYPOINT ["/bin/sh", "/usr/local/sbin/dhb-ax-debian-rootfs"]
