[kernel]
source = "tftp"
artifact = "artifacts/buildroot/uImage-hi3531-dhb-ax"
target = "uImage-hi3531-dhb-ax"
load_address = "0x82000000"

[rootfs]
source = "nfs"
artifact = "artifacts/debian/rootfs.tar"
export = "/srv/dhb-ax/debian-rootfs"
expected_os_id = "debian"

[boot]
action = "kernel"
args = [
  "console=ttyAMA0,115200",
  "earlycon=pl011,0x20080000",
  "ignore_loglevel",
  "mem=512M@0x80000000",
  "mem=512M@0xc0000000",
  "libata.force=2.00:norst,2.00:nodbdelay,2.01:norst,2.01:nodbdelay,2.03:norst,2.03:nodbdelay,2.04:norst,2.04:nodbdelay",
  "root=/dev/nfs",
  "nfsroot=${local.pi_ipaddr}:${rootfs.export},vers=3,tcp,nolock",
  "ip=${local.dvr_ipaddr}:::${local.dvr_netmask}:dvr:eth0:off",
  "rw",
]
hostname = "dvr"
