[kernel]
source = "usb"
artifact = "artifacts/buildroot/uImage-hi3531-dhb-ax"
target = "uImage"
usb_device = "0:1"

[rootfs]
source = "hdd"
artifact = "artifacts/debian/rootfs.cpio.gz"
device = "PARTUUID=8EBB5255-A43A-4B4E-953D-E81D2E0A2A6F"
label = "dhb-ax-debian"

[boot]
action = "kernel"
args = [
  "console=ttyAMA0,115200",
  "earlycon=pl011,0x20080000",
  "ignore_loglevel",
  "mem=512M@0x80000000",
  "mem=512M@0xc0000000",
  "libata.force=2.00:norst,2.00:nodbdelay,2.01:norst,2.01:nodbdelay,2.03:norst,2.03:nodbdelay,2.04:norst,2.04:nodbdelay",
  "rootfstype=ext4",
  "rootwait",
  "rw",
]
hostname = "dvr"
